// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: provider.proto

package provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type GetCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodeResponse) Reset() {
	*x = GetCodeResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodeResponse) ProtoMessage() {}

func (x *GetCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodeResponse.ProtoReflect.Descriptor instead.
func (*GetCodeResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []byte                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Meta          []byte                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *MessageRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MessageRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MessageRequest) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\bprovider\"\a\n" +
	"\x05Empty\"%\n" +
	"\x0fGetCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"z\n" +
	"\x0eMessageRequest\x12\x16\n" +
	"\x06params\x18\x01 \x01(\fR\x06params\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\fR\x04meta\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body2{\n" +
	"\x0fProviderService\x125\n" +
	"\aGetCode\x12\x0f.provider.Empty\x1a\x19.provider.GetCodeResponse\x121\n" +
	"\x04Send\x12\x18.provider.MessageRequest\x1a\x0f.provider.EmptyB\rZ\v./;providerb\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_provider_proto_goTypes = []any{
	(*Empty)(nil),           // 0: provider.Empty
	(*GetCodeResponse)(nil), // 1: provider.GetCodeResponse
	(*MessageRequest)(nil),  // 2: provider.MessageRequest
}
var file_provider_proto_depIdxs = []int32{
	0, // 0: provider.ProviderService.GetCode:input_type -> provider.Empty
	2, // 1: provider.ProviderService.Send:input_type -> provider.MessageRequest
	1, // 2: provider.ProviderService.GetCode:output_type -> provider.GetCodeResponse
	0, // 3: provider.ProviderService.Send:output_type -> provider.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
