syntax = "proto3";

package provider;

option go_package = "./;provider";

message Empty {}

message ConfigureRequest {
  bytes params = 1;
}

message MessageRequest {
  repeated string to = 1;
  bytes params = 2;
  string subject = 3;
  string body = 4;
}

message Response {
  string error = 1;
}

message MsgResponse {
  string response = 1;
  string error = 2;
  bool isCritical = 3;
}

service ProviderService {
  rpc Configure(ConfigureRequest) returns (Response);
  rpc Send(MessageRequest) returns (MsgResponse);
}
