// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthProviderService_Allow_FullMethodName = "/auth.AuthProviderService/Allow"
)

// AuthProviderServiceClient is the client API for AuthProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthProviderServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type authProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthProviderServiceClient(cc grpc.ClientConnInterface) AuthProviderServiceClient {
	return &authProviderServiceClient{cc}
}

func (c *authProviderServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowResponse)
	err := c.cc.Invoke(ctx, AuthProviderService_Allow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthProviderServiceServer is the server API for AuthProviderService service.
// All implementations must embed UnimplementedAuthProviderServiceServer
// for forward compatibility.
type AuthProviderServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
	mustEmbedUnimplementedAuthProviderServiceServer()
}

// UnimplementedAuthProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthProviderServiceServer struct{}

func (UnimplementedAuthProviderServiceServer) Allow(context.Context, *AllowRequest) (*AllowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Allow not implemented")
}
func (UnimplementedAuthProviderServiceServer) mustEmbedUnimplementedAuthProviderServiceServer() {}
func (UnimplementedAuthProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeAuthProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthProviderServiceServer will
// result in compilation errors.
type UnsafeAuthProviderServiceServer interface {
	mustEmbedUnimplementedAuthProviderServiceServer()
}

func RegisterAuthProviderServiceServer(s grpc.ServiceRegistrar, srv AuthProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthProviderService_ServiceDesc, srv)
}

func _AuthProviderService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderServiceServer).Allow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProviderService_Allow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderServiceServer).Allow(ctx, req.(*AllowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthProviderService_ServiceDesc is the grpc.ServiceDesc for AuthProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthProviderService",
	HandlerType: (*AuthProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _AuthProviderService_Allow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
